### PR TITLE
BasicFuncPrefix, indicating auth scope with array prefix URL.

### PR DESCRIPTION
**Pull request by yograterol**
HI,

My colaboration is about of BasicFunc, I did a change for add basic auth but discriminating the URL prefix.

By example:

If my app has:

```
/api/(...)
/dashboard/(...)
/admin/(...)
```

And just want basic auth in one url set I can't now, but with BasicFuncPrefix I can do it.

Use: 

``` go
import (
  "github.com/go-martini/martini"
  "github.com/martini-contrib/auth"
)

func main() {
  m := martini.Classic()
  // authenticate every request
  m.Use(auth.BasicFunc(func(username, password string) bool {
    return username == "admin" && password == "guessme"
  }, []string{"/api", "/private"})
  m.Run()
}
```

### CODE REVIEW

**Comment by rafecolton** [comment]
I believe what you're looking to do can be accomplished using the `Router`'s `Any` function.  Your code might look something like this:

```go
package main

import (
    "github.com/go-martini/martini"
    "github.com/martini-contrib/auth"
)

func main() {
    m := martini.Classic()
    authRoutes := []string{"/api", "/private"}
    for _, route := range authRoutes {
        m.Any(route, func(username, password string) bool {
            return username == "admin" && password == "guessme"
        })
    }
    m.Run()
}
```

**Comment by yograterol** [comment]
@rafecolton yep, but is it not more clean only declaring the BasicAuth with martini.Use?, I don't want declare all routes in the same file.

BTW, your solution is very very good...

**Comment by attilaolah** [comment]
First of all, as @rafecolton suggested, this can already be done with `Router.Any`.

Second, even if we would merge this, I would rather make the prefixes optional arguments to `BasicFunc` or `Basic`, something like:

``` go
func BasicFunc(authfn func(string, string) bool, prefixes ...string) martini.Handler {
    // …
}
```

**Comment by yograterol** [comment]
@attilaolah I can that it :) :+1:

**Pull request closed without merging**
