### PR TITLE
Added a function that makes it possible to use HTTP Basic auth only for certain URL prefixes

### PR DESCRIPTION
**Pull request by xyproto**
I have a simple REST API server that uses HTTP Basic auth only for the "/api" prefix. (https://github.com/xyproto/scoreserver)

By adding the BasicFuncPrefix function, this behavior is possible.

Also added a test.

### CODE REVIEW

**Comment by attilaolah** [comment]
This is basically a duplicate of #15.

**Comment by xyproto** [comment]
I see, I didn't notice. At least this demonstrates the interest in this functionality.

If there are no plans to add this functionality, could there please be an example for how to achieve the same result?

**Comment by attilaolah** [comment]
> could there please be an example for how to achieve the same result?

Maybe have a look at @rafecolton's commeent here: https://github.com/martini-contrib/auth/pull/15#issuecomment-71419638

I'm not saying this will not be added, but I'd like to be sure this is a needed functionality before we merge anything…

**Comment by xyproto** [comment]
The method in the other comment worked nicely. Thank you.

**Pull request closed without merging**
