### PR TITLE
Add auth.BasicFunc

### PR DESCRIPTION
**Pull request by attilaolah**
This only includes the implementation and some tests. Give me a moment and I'll update the README.

### CODE REVIEW

**Comment by schickling** [comment]
I'm still not sure how to inject something into the middleware e.g. a DB object.

**Comment by schickling** [comment]
@attilaolah @codegangsta could someone provide an example please?

**Comment by attilaolah** [comment]
@schickling just make it available to the closure you pass in to `auth.BasicFunc`, something like:

```go

db := dbSetup(…)
m.Use(auth.BasicFunc(func(username, password string) bool {
    user := db.Get(username)
    return user != nil && auth.SecureCompare(password, user.Password)
})

**Comment by schickling** [comment]
Is there another way by using the dependency injection inside via the `m.Use(...)` params? I don't think its a good idea to have a global db variable.

**Comment by attilaolah** [comment]
>  I don't think its a good idea to have a global db variable.

Of course it doesn't have to be global.

Currently `auth.BasicFunc` does not support Martini-style [DI]. What you can try instead, if you really don't like the closure, is to pass in a struct method instead:

```go
type DBAuth struct {
    db Database
}

func (a *DBAuth) auth(username, password string) bool {
    user := a.db.get(username)
    return user != nil && auth.SecureCompare(user.Password, password)
}

func main() {
    // …
    m.Use((&DBAuth{
        db: setUpDb(),
    }).auth)
}
```

This has basically the same effect as using a closure, only it uses a struct instead.

[DI]: //en.wikipedia.org/wiki/Dependency_injection

**Comment by schickling** [comment]
Thanks for the solution! Are there any plans to add DI to this project?

**Comment by attilaolah** [comment]
There were some discussions earlier, but I'm not sure anyone's too keen on implementing this. See #18.

I know the DI is cool but I still prefer good old closures or struct methods. But if you want to implement it, feel free to do so and send a PR.

**Pull request merged**
